openapi: 3.0.3
info:
  contact: {}
  description: "We're an AI video research company making personalized video possible\
    \ at scale. Generate videos of yourself, and never record again! Available via\
    \ web app & developer APIs."
  title: Tavus Developer API Collection
  version: 1.0.0
  x-konfig-has-globally-required-security: true
servers:
- url: https://tavusapi.com
security:
- apiKey: []
tags:
- name: Videos
- name: Replicas
paths:
  /v2/replicas:
    get:
      description: |
        This endpoint returns a list of all replicas that have been created by the API Key in use. In the response, a root level `data` key will contain the list of Replicas.
      operationId: Replicas_list
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReplicasListResponse'
      summary: List Replicas
      tags:
      - Replicas
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-replicas
      x-accepts: application/json
    post:
      description: "This endpoint creates a new Replica that can be used to generate\
        \ personalized videos. \n\nThe only required body parameter is `train_video_url`.\
        \ This url must be a download link such as a presigned S3 url. Please ensure\
        \ you pass in a video that meets the [requirements](https://docs.tavusapi.com/api-reference)\
        \ for training.\n\nReplica training will fail without the following consent\
        \ statement being present at the beginning of the video:\n> I, [FULL NAME],\
        \ am currently speaking and consent Tavus to create an AI clone of me by using\
        \ the audio and video samples I provide. I understand that this AI clone can\
        \ be used to create videos that look and sound like me.\n\nLearn more about\
        \ the consent statement [here](https://docs.tavusapi.com/api-reference).\n\
        \nLearn more about training a personal Replica [here](https://docs.tavusapi.com/api-reference).\n"
      operationId: Replicas_createNewReplica
      requestBody:
        content:
          application/json:
            examples:
              Create Replica:
                value:
                  callback_url: ""
                  replica_name: ""
                  train_video_url: ""
            schema:
              $ref: '#/components/schemas/ReplicasCreateNewReplicaRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReplicasCreateNewReplicaResponse'
      summary: Create Replica
      tags:
      - Replicas
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-replicas
      x-content-type: application/json
      x-accepts: application/json
  /v2/replicas/{replica_id}:
    delete:
      description: |
        This endpoint deletes a single Replica by its unique identifier. Once deleted, this Replica can not be used to generate videos.
      operationId: Replicas_deleteByReplicaId
      parameters:
      - explode: false
        in: path
        name: replica_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200": {}
      summary: Delete Replica
      tags:
      - Replicas
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--v2-replicas-replica_id
      x-accepts: application/json
    get:
      description: "This endpoint returns a single Replica by its unique identifier.\
        \ \n\nIncluded in the response body is a `training_progress` string that represents\
        \ the progress of the Replica training. If there are any errors during training,\
        \ the `status` will be `error` and the `error_message` will be populated.\n"
      operationId: Replicas_getReplicaById
      parameters:
      - explode: false
        in: path
        name: replica_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReplicasGetReplicaByIdResponse'
      summary: Get Replica
      tags:
      - Replicas
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-replicas-replica_id
      x-accepts: application/json
  /v2/replicas/{replica_id}/name:
    patch:
      description: "This endpoint renames a single Replica by its unique identifier.\
        \ \n"
      operationId: Replicas_renameReplicaById
      parameters:
      - explode: false
        in: path
        name: replica_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              Rename Replica:
                value:
                  replica_name: ""
            schema:
              $ref: '#/components/schemas/ReplicasRenameReplicaByIdRequest'
      responses:
        "200": {}
      summary: Rename Replica
      tags:
      - Replicas
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--v2-replicas-replica_id-name
      x-content-type: application/json
      x-accepts: application/json
  /v2/videos:
    get:
      description: "This endpoint returns a list of all videos that have been generated\
        \ by the API Key in use. \n"
      operationId: Videos_getAll
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideosGetAllResponse'
      summary: List Videos
      tags:
      - Videos
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-videos
      x-accepts: application/json
    post:
      description: "This endpoint generates a new video using a Replica and a script.\
        \ \n\nThe only required body parameters are `replica_id` and `script`. The\
        \ `replica_id` is a unique identifier for the Replica that will be used to\
        \ generate the video. The `script` is the text that will be spoken by the\
        \ Replica in the video.\n\nIf a `background_url` is provided, Tavus will record\
        \ a video of the website and use it as the background for the video. If a\
        \ `background_source_url` is provided, where the URL points to a download\
        \ link such as a presigned S3 URL, Tavus will use the video as the background\
        \ for the video. If neither are provided, the video will consist of a full\
        \ screen Replica.\n\nTo learn more about generating videos with Replicas,\
        \ see [here](https://docs.tavusapi.com/api-reference).\n\nTo learn more about\
        \ writing an effective script for your video, see [Scripting prompting](https://docs.tavusapi.com/api-reference).\n"
      operationId: Videos_createVideoFromReplicaAndScript
      requestBody:
        content:
          application/json:
            examples:
              Generate Video:
                value:
                  background_url: ""
                  replica_id: ""
                  script: ""
                  video_name: ""
            schema:
              $ref: '#/components/schemas/VideosCreateVideoFromReplicaAndScriptRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideosCreateVideoFromReplicaAndScriptResponse'
      summary: Generate Video
      tags:
      - Videos
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v2-videos
      x-content-type: application/json
      x-accepts: application/json
  /v2/videos/{video_id}:
    delete:
      description: |
        This endpoint deletes a single video by its unique identifier.
      operationId: Videos_deleteByVideoId
      parameters:
      - explode: false
        in: path
        name: video_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200": {}
      summary: Delete Video
      tags:
      - Videos
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--v2-videos-video_id
      x-accepts: application/json
    get:
      description: "This endpoint returns a single video by its unique identifier.\
        \ \n\nThe response body will contain a `status` string that represents the\
        \ status of the video. If the video is ready, the response body will also\
        \ contain a `download_url`, `stream_url`, and `hosted_url` that can be used\
        \ to download, stream, and view the video respectively.\n"
      operationId: Videos_getByVideoId
      parameters:
      - explode: false
        in: path
        name: video_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideosGetByVideoIdResponse'
      summary: Get Video
      tags:
      - Videos
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v2-videos-video_id
      x-accepts: application/json
  /v2/videos/{video_id}/name:
    patch:
      description: |
        This endpoint renames a single video by its unique identifier.
      operationId: Videos_updateName
      parameters:
      - explode: false
        in: path
        name: video_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              Rename Video:
                value:
                  video_name: ""
            schema:
              $ref: '#/components/schemas/VideosUpdateNameRequest'
      responses:
        "200": {}
      summary: Rename Video
      tags:
      - Videos
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--v2-videos-video_id-name
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    ReplicasCreateNewReplicaRequest:
      example:
        callback_url: callback_url
        train_video_url: train_video_url
        replica_name: replica_name
      properties:
        callback_url:
          description: A url that will receive a callback on completion of replica
            training or on error.
          type: string
        replica_name:
          description: A name for the replica.
          type: string
        train_video_url:
          description: A direct link to a publicly accessible storage location such
            as an S3 bucket. This video will be used for replica training.
          type: string
      required:
      - train_video_url
      type: object
    ReplicasRenameReplicaByIdRequest:
      example:
        replica_name: replica_name
      properties:
        replica_name:
          type: string
      required:
      - replica_name
      type: object
    VideosCreateVideoFromReplicaAndScriptRequest:
      example:
        video_name: My First Video
        replica_id: r783537ef5
        background_url: background_url
        background_source_url: background_source_url
        script: Hello from Tavus! Enjoy your new replica
      properties:
        background_source_url:
          description: A direct link to a video that is publicly accessible via a
            storage location such as an S3 bucket. This will be used as the background
            for the video. The video must be publicly accessible.
          type: string
        background_url:
          description: A link to a website. This will be used as the background for
            the video. The website must be publicly accessible and properly formed.
          type: string
        replica_id:
          description: A unique identifier for the replica that will be used to generate
            the video.
          example: r783537ef5
          type: string
          x-konfig-original-example: r783537ef5
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-VideosCreateVideoFromReplicaAndScriptRequest-properties-replica_id
        script:
          description: A script to be used for the video.
          example: Hello from Tavus! Enjoy your new replica
          type: string
          x-konfig-original-example: Hello from Tavus! Enjoy your new replica
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-VideosCreateVideoFromReplicaAndScriptRequest-properties-script
        video_name:
          description: A name for the video.
          example: My First Video
          type: string
          x-konfig-original-example: My First Video
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-VideosCreateVideoFromReplicaAndScriptRequest-properties-video_name
      required:
      - replica_id
      - script
      type: object
    VideosUpdateNameRequest:
      example:
        video_name: video_name
      properties:
        video_name:
          type: string
      required:
      - video_name
      type: object
    ReplicasListResponse:
      example:
        data:
        - thumbnail_video_url: thumbnail_video_url
          replica_id: r783537ef5
          created_at: created_at
          replica_name: My Replica
          status: completed
          training_progress: 100/100
        - thumbnail_video_url: thumbnail_video_url
          replica_id: r783537ef5
          created_at: created_at
          replica_name: My Replica
          status: completed
          training_progress: 100/100
      properties:
        data:
          items:
            $ref: '#/components/schemas/ReplicasListResponse_data_inner'
          type: array
      type: object
      x-konfig-is-used-in-successful-response: true
    ReplicasCreateNewReplicaResponse:
      example:
        replica_id: r783537ef5
        status: training
      properties:
        replica_id:
          description: A unique identifier for the replica.
          example: r783537ef5
          type: string
          x-konfig-original-example: r783537ef5
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-ReplicasCreateNewReplicaResponse-properties-replica_id
        status:
          description: The status of the replica.
          example: training
          type: string
          x-konfig-original-example: training
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-ReplicasCreateNewReplicaResponse-properties-status
      type: object
      x-konfig-is-used-in-successful-response: true
    ReplicasGetReplicaByIdResponse:
      example:
        error_message: error_message
        thumbnail_video_url: thumbnail_video_url
        replica_id: r783537ef5
        updated_at: 2024-01-24T07:14:03.327Z
        created_at: 2024-01-24T07:14:03.327Z
        replica_name: My Replica
        status: completed
        training_progress: 100/100
      properties:
        created_at:
          description: The date and time the replica was created.
          example: 2024-01-24T07:14:03.327Z
          type: string
          x-konfig-original-example: 2024-01-24T07:14:03.327Z
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-ReplicasGetReplicaByIdResponse-properties-created_at
        error_message:
          description: "If the replica has an error, this will contain the error message."
          nullable: true
          type: string
        replica_id:
          description: A unique identifier for the replica.
          example: r783537ef5
          type: string
          x-konfig-original-example: r783537ef5
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-ReplicasGetReplicaByIdResponse-properties-replica_id
        replica_name:
          description: The name of the replica.
          example: My Replica
          type: string
          x-konfig-original-example: My Replica
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-ReplicasGetReplicaByIdResponse-properties-replica_name
        status:
          description: The status of the replica.
          example: completed
          type: string
          x-konfig-original-example: completed
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-ReplicasGetReplicaByIdResponse-properties-status
        thumbnail_video_url:
          description: A direct link to the video that will be used as the thumbnail
            for the replica.
          type: string
        training_progress:
          description: The progress of the replica training.
          example: 100/100
          type: string
          x-konfig-original-example: 100/100
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-ReplicasGetReplicaByIdResponse-properties-training_progress
        updated_at:
          description: The date and time of when the replica was last updated.
          example: 2024-01-24T07:14:03.327Z
          type: string
          x-konfig-original-example: 2024-01-24T07:14:03.327Z
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-ReplicasGetReplicaByIdResponse-properties-updated_at
      type: object
      x-konfig-is-used-in-successful-response: true
    VideosGetAllResponse:
      example:
        data:
        - video_name: My First Video
          replica_id: r783537ef5
          background_url: background_url
          background_source_url: background_source_url
          script: Hello from Tavus! Enjoy your new replica
        - video_name: My First Video
          replica_id: r783537ef5
          background_url: background_url
          background_source_url: background_source_url
          script: Hello from Tavus! Enjoy your new replica
      properties:
        data:
          items:
            $ref: '#/components/schemas/VideosGetAllResponse_data_inner'
          type: array
      type: object
      x-konfig-is-used-in-successful-response: true
    VideosCreateVideoFromReplicaAndScriptResponse:
      example:
        video_name: video_name
        hosted_url: hosted_url
        created_at: created_at
        status: status
        video_id: video_id
      properties:
        created_at:
          description: The date and time the video was created.
          type: string
        hosted_url:
          description: "A direct link to view your video once generation has completed,\
            \ hosted by Tavus."
          type: string
        status:
          description: The status of the video.
          type: string
        video_id:
          description: A unique identifier for the video.
          type: string
        video_name:
          description: The name of the video.
          type: string
      type: object
      x-konfig-is-used-in-successful-response: true
    VideosGetByVideoIdResponse:
      example:
        data:
          script: script
        hosted_url: hosted_url
        updated_at: updated_at
        download_url: download_url
        created_at: created_at
        status_details: status_details
        stream_url: stream_url
        status: ready
        video_id: video_id
      properties:
        created_at:
          description: The date and time the video was created.
          type: string
        data:
          $ref: '#/components/schemas/VideosGetByVideoIdResponse_data'
        download_url:
          description: A direct link to download your generated video.
          type: string
        hosted_url:
          description: "A direct link to view your generated video, hosted by Tavus."
          type: string
        status:
          description: The status of the video.
          example: ready
          type: string
          x-konfig-original-example: ready
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-VideosGetByVideoIdResponse-properties-status
        status_details:
          description: A detailed status of the video.
          type: string
        stream_url:
          description: A direct link to stream your generated video.
          type: string
        updated_at:
          description: The date and time of when the video was last updated.
          type: string
        video_id:
          description: A unique identifier for the video.
          type: string
      type: object
      x-konfig-is-used-in-successful-response: true
    konfig-generated-schema-components-schemas-VideosCreateVideoFromReplicaAndScriptRequest-properties-replica_id:
      example: r783537ef5
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-VideosCreateVideoFromReplicaAndScriptRequest-properties-script:
      example: Hello from Tavus! Enjoy your new replica
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-VideosCreateVideoFromReplicaAndScriptRequest-properties-video_name:
      example: My First Video
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-ReplicasListResponse-properties-data-items-properties-replica_id:
      example: r783537ef5
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-ReplicasListResponse-properties-data-items-properties-replica_name:
      example: My Replica
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-ReplicasListResponse-properties-data-items-properties-status:
      example: completed
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-ReplicasListResponse-properties-data-items-properties-training_progress:
      example: 100/100
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-ReplicasCreateNewReplicaResponse-properties-replica_id:
      example: r783537ef5
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-ReplicasCreateNewReplicaResponse-properties-status:
      example: training
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-ReplicasGetReplicaByIdResponse-properties-created_at:
      example: 2024-01-24T07:14:03.327Z
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-ReplicasGetReplicaByIdResponse-properties-replica_id:
      example: r783537ef5
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-ReplicasGetReplicaByIdResponse-properties-replica_name:
      example: My Replica
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-ReplicasGetReplicaByIdResponse-properties-status:
      example: completed
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-ReplicasGetReplicaByIdResponse-properties-training_progress:
      example: 100/100
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-ReplicasGetReplicaByIdResponse-properties-updated_at:
      example: 2024-01-24T07:14:03.327Z
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-VideosGetAllResponse-properties-data-items-properties-replica_id:
      example: r783537ef5
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-VideosGetAllResponse-properties-data-items-properties-script:
      example: Hello from Tavus! Enjoy your new replica
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-VideosGetAllResponse-properties-data-items-properties-video_name:
      example: My First Video
      type: string
      x-do-not-generate: true
    konfig-generated-schema-components-schemas-VideosGetByVideoIdResponse-properties-status:
      example: ready
      type: string
      x-do-not-generate: true
    konfig-generated-schema-single-parameter-schema-get--v2-replicas:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-post--v2-replicas:
      properties:
        callback_url:
          description: A url that will receive a callback on completion of replica
            training or on error.
          type: string
        replica_name:
          description: A name for the replica.
          type: string
        train_video_url:
          description: A direct link to a publicly accessible storage location such
            as an S3 bucket. This video will be used for replica training.
          type: string
      required:
      - train_video_url
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-delete--v2-replicas-replica_id:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-get--v2-replicas-replica_id:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-patch--v2-replicas-replica_id-name:
      properties:
        replica_name:
          type: string
      required:
      - replica_name
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-get--v2-videos:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-post--v2-videos:
      properties:
        background_source_url:
          description: A direct link to a video that is publicly accessible via a
            storage location such as an S3 bucket. This will be used as the background
            for the video. The video must be publicly accessible.
          type: string
        background_url:
          description: A link to a website. This will be used as the background for
            the video. The website must be publicly accessible and properly formed.
          type: string
        replica_id:
          description: A unique identifier for the replica that will be used to generate
            the video.
          example: r783537ef5
          type: string
          x-konfig-original-example: r783537ef5
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-VideosCreateVideoFromReplicaAndScriptRequest-properties-replica_id
        script:
          description: A script to be used for the video.
          example: Hello from Tavus! Enjoy your new replica
          type: string
          x-konfig-original-example: Hello from Tavus! Enjoy your new replica
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-VideosCreateVideoFromReplicaAndScriptRequest-properties-script
        video_name:
          description: A name for the video.
          example: My First Video
          type: string
          x-konfig-original-example: My First Video
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-VideosCreateVideoFromReplicaAndScriptRequest-properties-video_name
      required:
      - replica_id
      - script
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-delete--v2-videos-video_id:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-get--v2-videos-video_id:
      properties: {}
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    konfig-generated-schema-single-parameter-schema-patch--v2-videos-video_id-name:
      properties:
        video_name:
          type: string
      required:
      - video_name
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter: []
    ReplicasListResponse_data_inner:
      example:
        thumbnail_video_url: thumbnail_video_url
        replica_id: r783537ef5
        created_at: created_at
        replica_name: My Replica
        status: completed
        training_progress: 100/100
      properties:
        created_at:
          type: string
        replica_id:
          description: A unique identifier for the replica.
          example: r783537ef5
          type: string
          x-konfig-original-example: r783537ef5
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-ReplicasListResponse-properties-data-items-properties-replica_id
        replica_name:
          description: The name of the replica.
          example: My Replica
          type: string
          x-konfig-original-example: My Replica
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-ReplicasListResponse-properties-data-items-properties-replica_name
        status:
          description: The status of the replica.
          example: completed
          type: string
          x-konfig-original-example: completed
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-ReplicasListResponse-properties-data-items-properties-status
        thumbnail_video_url:
          description: A direct link to the video that will be used as the thumbnail
            for the replica.
          type: string
        training_progress:
          description: The progress of the replica training.
          example: 100/100
          type: string
          x-konfig-original-example: 100/100
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-ReplicasListResponse-properties-data-items-properties-training_progress
      type: object
    VideosGetAllResponse_data_inner:
      example:
        video_name: My First Video
        replica_id: r783537ef5
        background_url: background_url
        background_source_url: background_source_url
        script: Hello from Tavus! Enjoy your new replica
      properties:
        background_source_url:
          description: A direct link to a video that is publicly accessible via a
            storage location such as an S3 bucket. This will be used as the background
            for the video. The video must be publicly accessible.
          type: string
        background_url:
          description: A link to a website. This will be used as the background for
            the video. The website must be publicly accessible and properly formed.
          type: string
        replica_id:
          description: A unique identifier for the replica that will be used to generate
            the video.
          example: r783537ef5
          type: string
          x-konfig-original-example: r783537ef5
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-VideosGetAllResponse-properties-data-items-properties-replica_id
        script:
          description: A script to be used for the video.
          example: Hello from Tavus! Enjoy your new replica
          type: string
          x-konfig-original-example: Hello from Tavus! Enjoy your new replica
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-VideosGetAllResponse-properties-data-items-properties-script
        video_name:
          description: A name for the video.
          example: My First Video
          type: string
          x-konfig-original-example: My First Video
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-VideosGetAllResponse-properties-data-items-properties-video_name
      type: object
    VideosGetByVideoIdResponse_data:
      example:
        script: script
      properties:
        script:
          description: The script that was initially used to generate the video.
          type: string
      type: object
  securitySchemes:
    apiKey:
      in: header
      name: x-api-key
      type: apiKey
      x-konfig-globally-required-security: true

